part of '../themes/themes.dart';

const _lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: LightColors.primary,
  surfaceTint: LightColors.surfaceTint,
  onPrimary: LightColors.onPrimary,
  primaryContainer: LightColors.primaryContainer,
  onPrimaryContainer: LightColors.onPrimaryContainer,
  secondary: LightColors.secondary,
  onSecondary: LightColors.onSecondary,
  secondaryContainer: LightColors.secondaryContainer,
  onSecondaryContainer: LightColors.onSecondaryContainer,
  tertiary: LightColors.tertiary,
  onTertiary: LightColors.onTertiary,
  tertiaryContainer: LightColors.tertiaryContainer,
  onTertiaryContainer: LightColors.onTertiaryContainer,
  error: LightColors.error,
  onError: LightColors.onError,
  errorContainer: LightColors.errorContainer,
  onErrorContainer: LightColors.onErrorContainer,
  surface: LightColors.surface,
  onSurface: LightColors.onSurface,
  surfaceContainerHighest: LightColors.surfaceVariant,
  onSurfaceVariant: LightColors.onSurfaceVariant,
  outline: LightColors.outline,
  outlineVariant: LightColors.outlineVariant,
  shadow: LightColors.shadow,
  scrim: LightColors.scrim,
  inverseSurface: LightColors.inverseSurface,
  inversePrimary: LightColors.inversePrimary,
  onInverseSurface: LightColors.onInverseSurface,
  
);
